# Generated by Django 5.0.4 on 2024-04-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_complainroom_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintype',
            old_name='name',
            new_name='complainType',
        ),
    ]
