# Generated by Django 5.0.4 on 2024-04-13 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_complaintype_complaintype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplainRoom',
            new_name='ComplaintRoom',
        ),
        migrations.RenameModel(
            old_name='ComplainType',
            new_name='ComplaintType',
        ),
        migrations.RenameField(
            model_name='complaintroom',
            old_name='complainType',
            new_name='complaintType',
        ),
        migrations.RenameField(
            model_name='complainttype',
            old_name='complainType',
            new_name='complaintType',
        ),
    ]
