# Generated by Django 5.0.4 on 2024-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mess',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
