# Generated by Django 5.0.4 on 2024-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintroom',
            name='cid',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
