# Generated by Django 5.0.4 on 2024-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_complaintroom_area_complaintroom_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
