# Generated by Django 5.0.4 on 2024-11-12 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_complaintroom_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintroom',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='complaintType',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Civil', 'Civil'), ('Mess', 'Mess'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
